name: "🚀 Feature Request"
description: "I have a suggestion for Aptakube!"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: |
        A concise description of what the problem is.
      placeholder: |
        I have an issue when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
